#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChangeThatTrack.Resource", IsApplication=true)]

namespace ChangeThatTrack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int down = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int downpressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int main = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int next = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int NextButton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int nextpressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pause = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int PauseButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pausepressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int play = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int PlayButton = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int playpressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int prev = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int PrevButton = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int prevpressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int roundback = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int roundbutton = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int up = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int uppressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int VolumeDown = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int VolumeUp = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int barVolume = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int btnAddToList = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btnEnterIP = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int btnNext = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int btnPlay = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int btnPrev = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int btnSaveIP = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int btnVolumeDown = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int btnVolumeUp = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int editTxtIP = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int editTxtIPToSave = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int editTxtName = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int imageView1 = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int listViewIP = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int tablerow = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddIPDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EnterIP = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ThemeWithActionBar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
